// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using referenciamento.api.ORM;

namespace referenciamento.api.Migrations
{
    [DbContext(typeof(ReferenciamentoDbContext))]
    [Migration("20220131001936_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("referenciamento.api.Domain.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AnoAtualizacaoSituacao")
                        .HasColumnType("integer");

                    b.Property<int>("ArquivoMorto")
                        .HasColumnType("integer");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataRef")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("RG")
                        .HasColumnType("text");

                    b.Property<int>("SituacaoCadastro")
                        .HasColumnType("integer");

                    b.Property<string>("TecRef")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("referenciamento.api.Domain.ProntuarioProgramaSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DomicilioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramaSocial")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DomicilioId");

                    b.ToTable("ProntuarioProgramaSocial");
                });

            modelBuilder.Entity("referenciamento.api.Domain.ProntuarioProgramaSocial", b =>
                {
                    b.HasOne("referenciamento.api.Domain.Prontuario", "Domicilio")
                        .WithMany("Programas")
                        .HasForeignKey("DomicilioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domicilio");
                });

            modelBuilder.Entity("referenciamento.api.Domain.Prontuario", b =>
                {
                    b.Navigation("Programas");
                });
#pragma warning restore 612, 618
        }
    }
}
